// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzPkkwWSvO4zrxIbowUBfY-WVKKC_zZx0',
    appId: '1:494796446601:android:25d222b687682676d41f58',
    messagingSenderId: '494796446601',
    projectId: 'simple-fire-auth-55573',
    storageBucket: 'simple-fire-auth-55573.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMi0pg-AOP3UTenC6X2L0RCG7FPFVy-d8',
    appId: '1:494796446601:ios:aa11e7b60cf88e1cd41f58',
    messagingSenderId: '494796446601',
    projectId: 'simple-fire-auth-55573',
    storageBucket: 'simple-fire-auth-55573.appspot.com',
    androidClientId: '494796446601-sarqnq6ngjnk1r6427r229lb5vddb1m8.apps.googleusercontent.com',
    iosClientId: '494796446601-jjgaf9591fsptu01q2sf9mhqe2mnp73j.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleLoginFirebase',
  );
}
